# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: Anders
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerHub'
        repository: | 
          dreamstream/broker
        command: 'buildAndPush'
        Dockerfile: './Dream-Stream/Dockerfile'
        buildContext: '.'
        tags: |
          $(tag)
- stage: Release
  displayName: Build image
  jobs:  
  - job: Release
    displayName: Release
    pool: Anders
    steps:
    - task: Kubernetes@0
      displayName: 'kubectl apply'
      inputs:
        kubernetesServiceConnection: KubeAnders
        command: apply
        arguments: '-f ./kubectl.yaml'