apiVersion: v1
kind: Service
metadata:
  name: broker-0
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: broker-0
  ports:
  - name: web
    protocol: TCP
    nodePort: 30030
    targetPort: 80
    port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: broker
# spec:
#   externalTrafficPolicy: Local
#   ports:
#   - nodePort: 30000
#     port: 30000
#     protocol: TCP
#     targetPort: 9092
#   selector:
#     app: broker
#   type: NodePort