apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: broker-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: broker-0
  ports:
  - name: web
    protocol: TCP
    port: 81
    targetPort: 80