apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
  labels:
    app: broker
    k8s-app: prometheus
spec:
  selector:
    matchLabels:
      app: broker
  serviceName: "broker"
  replicas: 3
  template:
    metadata:
      labels:
        app: broker
        k8s-app: prometheus
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: dreamstream/broker:264
        ports:
        - containerPort: 80
          name: broker
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:80"
        - name: LOCAL_STORAGE
          value: "TRUE"
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
        volumeMounts:
          - name: file-storage
            mountPath: /ssd/local
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: storage-local-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-local-claim
spec:
  storageClassName: csi-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 9Gi