apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
  labels:
    app: broker
    k8s-app: prometheus
spec:
  selector:
    matchLabels:
      app: broker
  serviceName: "broker"
  replicas: 3
  template:
    metadata:
      labels:
        app: broker
        k8s-app: prometheus
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: dreamstream/broker:194
        ports:
        - containerPort: 80
          name: broker
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:80"
        - name: STORAGE_METHOD
          value: "API"
      #   volumeMounts:
      #   - name: file-writing
      #     mountPath: /mnt/data
      # volumes:
      # - name: file-writing
      #   persistentVolumeClaim:
      #     claimName: broker-claim
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: broker-claim
# spec:
#   storageClassName: csi-cephfs
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 3Gi
