apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  serviceName: "broker"
  replicas: 3
  template:
    metadata:
      labels:
        app: broker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: dreamstream/broker:164
        ports:
        - containerPort: 80
          name: broker
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:80"



          